Merge front_responsive to master
Esc-IngComp-UNC/computer-laboratory-web-page pull request #8
Opened 2024-11-08 00:02 UTC by MatiSalinas

### Pull Request Description

#### What does this PR do?
This pull request addresses the responsiveness of the frontend and refactors the FormLab component to use `react-hook-form` for better form management. It includes the following changes:

- Disables animations on the News component for mobile devices.
- Adds media queries for devices with a screen width of 800px or less, optimizing the layout for smaller screens.
- Transforms the navbar into a mobile-friendly menu using the `isMobile` flag to provide different layouts for mobile and desktop views.
- Rewrites the FormLab component to use `react-hook-form` for handling form data and integrates `zod` for form validation.

#### Changes Made:
1. **Animations in News Component:**
   - Introduced a flag (`isMobile`) to disable `framer-motion` animations on mobile devices, improving the user experience on smaller screens.
  
2. **Mobile Responsiveness:**
   - Added media queries targeting screens 800px and below.
   - Adjusted the layout by switching from `flex` to `column` for most elements and setting component widths to `100vw`.

3. **Navbar Refactor:**
   - Used the `isMobile` flag to provide a responsive menu, replacing the traditional navbar with a collapsible menu on mobile devices.

4. **FormLab Refactor:**
   - Replaced the form state management with `react-hook-form`'s `register` method.
   - Integrated `zod` for schema-based validation, ensuring consistent validation and error handling.

#### Related Issues:
- [Link to related issue #7](https://github.com/Esc-IngComp-UNC/computer-laboratory-web-page/issues/7)

2024-11-08 00:31 UTC, prietojulii commented
Great job, Mat! I only have a few comments

2024-11-08 00:43 UTC, prietojulii commented on web/src/App.css
> +  background-color: #f2f3f4;
We can use CSS variables to make maintenance easier. For example, colors could be placed in variables and reused

2024-11-08 00:43 UTC, prietojulii commented on web/src/App.jsx
> +        <Element name="aboutUs">
The words displayed to the user must be in Spanish

2024-11-08 00:43 UTC, prietojulii commented on web/src/App.jsx
> +        <Element name="faq">
the same here

2024-11-08 00:43 UTC, prietojulii commented on web/src/components/Contact.jsx
> +    //TODO add SVG to each link
This comment can be deleted?

2024-11-08 00:43 UTC, prietojulii commented on web/.gitkeep
this file can be deleted

2024-11-08 00:43 UTC, prietojulii commented on web/index.html
> +    <title>Laboratorio Computacion</title>
```suggestion
    <title>Laboratorio de Computación</title>
```

2024-11-08 01:02 UTC, prietojulii commented on web/src/components/Contact.jsx
> +import twitter from '/svgs/twitterx.svg'
We havent twitter or youtube. Can you delete them?

2024-11-08 01:05 UTC, prietojulii commented on web/src/components/Contact.jsx
> +            <p>Instagram: c.fcefyn</p>
```suggestion
            <div className="socialMedia">
                <img src={instagram} alt="InstagramLogo" />
            <a target='_blank' href='https://www.instagram.com/lc.fcefyn/'>Instagram</a>
            </div>
```

2024-11-08 01:06 UTC, prietojulii commented on web/src/components/Contact.jsx
> +            <p>Correo: lc.fcefyn@gmail.com</p>
Can we use an image/icon for GMAIL. For example https://upload.wikimedia.org/wikipedia/commons/7/7e/Gmail_icon_%282020%29.svg

2024-11-08 01:29 UTC, prietojulii commented on web/src/components/MapGoogle.jsx
> +        <div className="mapa"><iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d13617.083057234764!2d-64.181348!3d-31.434212!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses-419!2sar!4v1727935597
```suggestion
        <div className="mapa"><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13617.083057234764!2d-64.181348!3d-31.434212!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9432a2f54d372bf1%3A0xf1d83ddc363cda16!2sFacultad%20de%20Ciencias%20Exactas%2C%20F%C3%ADsicas%20y%20Naturales!5e0!3m2!1ses-419!2sar!4v1731029204729!5m2!1ses-419!2sar" width={'100%'}  height={600} style={{border:0}} allowFullScreen={''} loading={"lazy"} referrerPolicy={"no-referrer-when-downgrade"}></iframe></div>
```

2024-11-08 01:29 UTC, prietojulii commented on web/src/components/MapGoogle.jsx
> +        <div className="mapa"><iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d13617.083057234764!2d-64.181348!3d-31.434212!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses-419!2sar!4v1727935597
Esto marca un punto rojo en la ubicación

2024-11-08 03:09 UTC, prietojulii commented on web/src/App.jsx
> +        <Element name="aboutUs">
Maintain the order of the menu with the presentation order.
1- aboutus
2- novedades
3- faq
4-contacto

2024-11-08 04:00 UTC, prietojulii commented on web/src/components/Contact.jsx
> +            <a target='_blank' href='https://twitter.com/FCEFyN_UNC' >twitter</a>
```suggestion
            <a target='_blank' href='https://twitter.com/fcefyn_unc' >twitter</a>
```

2024-11-08 04:02 UTC, prietojulii commented on web/src/components/Contact.jsx
> +    //TODO add SVG to each link
```suggestion
```

2024-11-08 06:40 UTC, MatiSalinas commented
Thanks for your feedback, I made the suggested changes in the last commit [0aa27ba](https://github.com/Esc-IngComp-UNC/computer-laboratory-web-page/pull/8/commits/0aa27ba183043bea8ecdc585a149fdea1c351891).

2024-11-09 04:02 UTC, prietojulii commented
It's amazing! Good Job!

2024-11-09 04:03 UTC, prietojulii approved these changes

2024-11-20 19:13 UTC, prietojulii approved these changes

2024-11-28 12:27 UTC, GabrielEValenzuela requested changes
Great work Mati! 

Please check missing endlines and one little improvement on the path

2024-11-28 12:27 UTC, GabrielEValenzuela commented on web/src/main.jsx
> +import App from './App.jsx'
```suggestion
import App from '@/src/App.jsx'
```

2024-12-04 00:25 UTC, MatiSalinas commented
added endline and changed path on [27635ab](https://github.com/Esc-IngComp-UNC/computer-laboratory-web-page/commit/27635aba63d92699104e06b16fba4c6528c3aa9f).

2024-12-04 12:13 UTC, GabrielEValenzuela approved these changes
LGTM

2024-12-04 12:13 UTC, merged